version: '3.9'

services:
  talker:
    image: osrf/ros:humble-desktop
    command: ros2 run demo_nodes_cpp talker
    network_mode: host
    ipc: host

  listener:
    image: osrf/ros:humble-desktop
    command: ros2 run demo_nodes_cpp listener
    depends_on:
      - talker
    network_mode: host
    ipc: host

  zenoh-bridge:
    image: eclipse/zenoh-bridge-dds:latest
    command: -e tcp/localhost:7447 -a /chatter
    ipc: host
    network_mode: host
  
  router:
    image: eclipse/zenoh
    restart: unless-stopped
    ipc: host
    network_mode: host
    # ports:
    #   - 7447:7447
    #   - 8000:8000
    # volumes:
    #   - ./zenoh_docker:/root/.zenoh
    environment:
      - RUST_LOG=debug
