services:
  talker:
    image: osrf/ros:humble-desktop
    command: ros2 run demo_nodes_cpp talker
    network_mode: host
    ipc: host

  listener:
    image: osrf/ros:humble-desktop
    command: ros2 run demo_nodes_cpp listener
    depends_on:
      - talker
    network_mode: host
    ipc: host

  bridge:
    image: eclipse/zenoh-bridge-dds:latest
    command: -c /etc/zenohd/zenohd.yaml
    volumes:
      - ./zenohd.yml:/etc/zenohd/zenohd.yaml
    network_mode: host
    ipc: host

  router:
    image: eclipse/zenoh
    restart: unless-stopped
    ipc: host
    network_mode: host
    environment:
      - RUST_LOG=debug
