services:
  talker:
    build:
      context: ./publisher
    command: publisher -r /app/publisher/timescales/largesuite/RecurGLB/RecurGLB10.jsonl
    # network_mode: host
    networks:
      - zenoh

  reelayd:
    build:
      context: ./reelayd
    command: reelayd --expr "{p}"
    # network_mode: host
    networks:
      - zenoh
  
  # router:
  #   image: eclipse/zenoh
  #   restart: unless-stopped
  #   networks:
  #     - zenoh
  #   ports:
  #     - 7447:7447
  #     - 8000:8000

networks:
  zenoh:
    driver: bridge
