######################## stage 1 ######################### 
# Build ./subscriber
FROM ghcr.io/bounverif/boostdevel:latest as builder_subscriber

ARG ZENOH_VERSION=0.10.1-rc
ARG ZENOHC_VERSION=${ZENOH_VERSION}
ARG REELAY_VERSION=main
ARG SIMDJSON_VERSION=3.9.1

ARG RUST_VERSION=1.72.1
ARG RUST_PROFILE=minimal
ARG RUST_TOOLCHAIN=${RUST_VERSION}-x86_64-unknown-linux-gnu
ENV CARGO_HOME="/usr/local/cargo"

ENV RUSTUP_HOME="/usr/local/rustup"
ENV PATH "/usr/local/cargo/bin:/usr/local/rustup:${PATH}"

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
    sh -s -- -y --no-modify-path --profile ${RUST_PROFILE} --default-toolchain ${RUST_VERSION}

RUN git clone --depth 1 --branch ${ZENOHC_VERSION} https://github.com/eclipse-zenoh/zenoh-c.git /tmp/zenoh-c && \
    cmake -S/tmp/zenoh-c -B/tmp/zenoh-c/build \
        -DCMAKE_BUILD_TYPE=Release \
        -DZENOHC_CARGO_CHANNEL=${RUST_TOOLCHAIN} \
        -DZENOHC_INSTALL_STATIC_LIBRARY=TRUE \
    && cmake --build /tmp/zenoh-c/build/ --target install -j$(nproc) \
    && rm -rf /tmp/zenoh-c

COPY ./subscriber /app/
WORKDIR /app/

RUN cmake --preset default && \
    cmake --build  --target install -j$(nproc) --preset default 

######################## stage 2 ######################### 
# Build CycloneDDS from source
FROM debian:bookworm-slim as builder_cyclone

RUN apt update && apt install -y \
        cmake \
        g++ \
        git

ARG CYCLONEDDS_VERSION=0.10.2
# Options: Debug, Release, RelWithDebInfo, MinSizeRel:  -DCMAKE_BUILD_TYPE=${CYCLONEDDS_BUILD_TYPE}
ARG CYCLONEDDS_BUILD_TYPE=RelWithDebInfo

RUN git clone https://github.com/eclipse-cyclonedds/cyclonedds.git /cyclonedds && \
    cd /cyclonedds && \
    git checkout --quiet ${CYCLONEDDS_VERSION} && \
    mkdir build install && \
    cd build
WORKDIR /cyclonedds/build
RUN cmake .. -DCMAKE_INSTALL_PREFIX="/cyclonedds/install/"
RUN cmake --build . --target install -j$(nproc)

######################## stage 3 ######################### 
## Final image
FROM debian:bookworm-slim
ENV DEBIAN_FRONTEND=noninteractive

## Install Zenohd and its DDS plugin

# This version should match one of the output of `apt-cache policy zenohd` or `apt-cache madison zenohd`
ARG ZENOHD_VERSION=0.10.1-rc-1

RUN apt-get update && apt-get upgrade -y

# dependencies for zenohd, a post-install script requires sudo and systemctl
RUN apt-get install -y dpkg sudo systemctl

# This repo is not reliable. Sometimes it is not available.
RUN echo "deb [trusted=yes] https://download.eclipse.org/zenoh/debian-repo/ /" | sudo tee -a /etc/apt/sources.list > /dev/null
RUN apt-get update

RUN apt-get install -y zenohd=${ZENOHD_VERSION}
RUN apt-get install -y zenoh-bridge-dds=${ZENOHD_VERSION}
RUN apt-get install -y zenoh-plugin-rest=${ZENOHD_VERSION}

# Install supervisord
RUN apt-get install -y supervisor

## Copy subscriber from builder_subscriber
COPY --from=builder_subscriber /usr/local/bin/subscriber /usr/local/bin

## Copy cyclonedds from builder_cyclone
ENV CYCLONEDDS_HOME=/usr/local/cyclonedds/
ENV PATH="${CYCLONEDDS_HOME}/bin:${PATH}"
COPY --from=builder_cyclone /cyclonedds/install/ ${CYCLONEDDS_HOME}

## Copy the config and set the entrypoint
COPY ./zenohd.yaml /etc/zenohd/zenohd.yaml
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Specify the entrypoint
CMD ["/usr/bin/supervisord"]