services:
  talker:
    build:
      context: .
    command: ./cxxRoundtripPing 64 100
    # command: ./cxxRoundtripPing [payloadSize (bytes, 0 - 655536)] [numSamples (0 = infinite)] [timeOut (seconds, 0 = infinite)]
    # network_mode: host
    #   # - dds_network
    networks:
      - dds
    

  listener:
    build:
      context: .
    command: ./cxxRoundtripPong
    # network_mode: host
      # - dds_network
    networks:
      - dds
  
#   router:
#     image: eclipse/zenoh
#     restart: unless-stopped
#     networks:
#       - zenoh
#     ports:
#       - 7447:7447
#       - 8000:8000

networks:
  dds:
    driver: bridge
