# Use the Boost development image as the base for building
FROM ghcr.io/bounverif/boostdevel:latest as builder

ARG ZENOH_VERSION=0.10.1-rc
ARG ZENOHC_VERSION=${ZENOH_VERSION}
ARG REELAY_VERSION=main
ARG SIMDJSON_VERSION=3.9.1

ARG RUST_VERSION=1.72.1
ARG RUST_PROFILE=minimal
ARG RUST_TOOLCHAIN=${RUST_VERSION}-x86_64-unknown-linux-gnu
ENV CARGO_HOME="/usr/local/cargo"
ENV RUSTUP_HOME="/usr/local/rustup"
ENV PATH="/usr/local/cargo/bin:/usr/local/rustup:${PATH}"

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
    sh -s -- -y --no-modify-path --profile ${RUST_PROFILE} --default-toolchain ${RUST_VERSION}

# Clone and build Zenoh-C
RUN git clone --depth 1 --branch ${ZENOHC_VERSION} https://github.com/eclipse-zenoh/zenoh-c.git /tmp/zenoh-c && \
    cmake -S/tmp/zenoh-c -B/tmp/zenoh-c/build \
        -DCMAKE_BUILD_TYPE=Release \
        -DZENOHC_CARGO_CHANNEL=${RUST_TOOLCHAIN} \
        -DZENOHC_INSTALL_STATIC_LIBRARY=TRUE \
    && cmake --build /tmp/zenoh-c/build/ --target install -j$(nproc) \
    && rm -rf /tmp/zenoh-c

# Build publisher
COPY ./publisher /app/publisher
WORKDIR /app/publisher
RUN cmake --preset default && cmake --build --target install -j$(nproc) --preset default

# Build subscriber
COPY ./subscriber /app/subscriber
WORKDIR /app/subscriber
RUN cmake --preset default && cmake --build --target install -j$(nproc) --preset default

# Final stage
FROM debian:bookworm-slim

# Install Supervisor
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y \
      supervisor \
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# Copy files from the builder stage
COPY --from=builder /usr/local/bin/publisher /usr/local/bin
COPY --from=builder /usr/local/bin/subscriber /usr/local/bin

# Copy the supervisord configuration
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Set the working directory
WORKDIR /app

# Start supervisord
CMD ["/usr/bin/supervisord"]
